theme: jekyll-theme-minimal
title: DIGISURVOR Workshop: ‘Linking Digital Footprint and Survey Data for Open Research’ 13-14th February 2025.
description: This public page contains slide decks from presenters at the DIGISURVOR workshop and other relevant documents. 
